# Hourly scraping
name: buildWallet

# Controls when the action will run.
#on:
#  # Triggers the workflow on push or pull request events but only for the master branch
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]
#  # Allows you to run this workflow manually from the Actions tab
on:
  schedule:
    - cron:  "0 * * * *"
  workflow_dispatch:
    
jobs: 
  createWallet:
    # The type of runner that the job will run on
    runs-on: macOS-latest

    # Load repo and install R
    steps:
    - uses: actions/checkout@master
    - uses: r-lib/actions/setup-r@master
      with:
         r-version: '4.1.1'
    - uses: r-lib/actions/setup-pandoc@v1

    # When adding a new package: Remove this section and run the code first, then add this section again
    # - name: Cache R packages
    #    id: cache
    #    uses: actions/cache@v2
    #    with:
    #      path: ${{ env.R_LIBS_USER }}
    #      key: ${{ runner.os }}-shinydoc
    #      restore-keys: |
    #        ${{ runner.os }}-
          
    - name: Install packages
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        install.packages(c("rmarkdown", "kableExtra", "data.table", "magrittr", "geckor"))
      shell: Rscript {0}
        
    - name: Build
      run: |
        rmarkdown::render('mywallet.Rmd', output_file = 'wallets/mywallet_mathias.html', params = list(user = "mathias"))
        rmarkdown::render('mywallet.Rmd', output_file = 'wallets/mywallet_martin.html', params = list(user = "martin"))
        rmarkdown::render('mywallet.Rmd', output_file = 'wallets/mywallet_margaux.html', params = list(user = "margaux"))
        rmarkdown::render('mywallet.Rmd', output_file = 'wallets/mywallet_sebastian.html', params = list(user = "sebastian"))
        rmarkdown::render('mywallet.Rmd', output_file = 'wallets/mywallet_claudine.html', params = list(user = "claudine"))
        rmarkdown::render('mywallet.Rmd', output_file = 'wallets/mywallet_total.html', params = list(user = "total"))
      shell: Rscript {0}
      
 # Add new files in data folder, commit along with other modified files, push
    - name: Commit files
      run: |
        git config --local user.name actions-user
        git config --local user.email "actions@github.com"
        git add wallets/*
        git commit -am "Wallet updated $(date)"
        git push origin
      env:
        REPO_KEY: ${{secrets.GITHUB_TOKEN}}
        username: github-actions
